### ISSUE TITLE
Missing files in Snapshots cache

### ISSUE THREAD

**Issue by notoriousturtle** [chaitin/passionfruit#39]
The file browser is not showing all files under:

`guid/Library/Caches/Snapshots/target/`

Expecting it to show all files, whether Passionfruit can open them or not.

**Comment by Daemonceltics** [comment]
Bug confirmed! Because sandbox kernel deny app read Library/Caches/Snapshots directory in iOS 11

**Comment by ChiChou** [comment]
On iOS 11, the app itself is no longer allowed to access this directory.
In the latest commit, we will show an error to make it clear: `failed to change current directory: Error: The file “Snapshots” couldn’t be opened because you don’t have permission to view it.`

You can still fetch the files via SSH since sshd is not sandboxed
