### ISSUE TITLE
Network connection instead of USB?

### ISSUE THREAD

**Issue by sushi2k** [chaitin/passionfruit#50]
Hi, 

I have a special scenario where I would need to connect via network to the frida-server instead via USB. 

Is this on the roadmap also for passionfruit or can I configure this somewhere? For example with objection flags are available for network connections via Frida. 

Thanks

![image](https://user-images.githubusercontent.com/5951320/59564961-b6956080-907f-11e9-9a50-5518b1c561f6.png)

**Comment by ChiChou** [comment]
Thank you for reporting. It's on the roadmap.

**Comment by sushi2k** [comment]
Any ETA for this @ChiChou?

**Comment by evandrix** [comment]
*bump*

**Comment by ChiChou** [comment]
I admit that since I left Chaitin this project is not so actively maintained.

I've left some uncommitted changes in an offline computer in Beijing. That is some radical refactoring so I tend to avoid new changes in master branch until I finish it. Unfortunately the nCoV outbreak makes it unclear when it'll finally be safe to go back. I've been staying home for two weeks.

I am sorry for the inconvenience.

**Comment by sushi2k** [comment]
Thanks for all your hard work on this project, stay safe and take care @ChiChou! Hope everything is soon back to normal for you.

**Comment by ChiChou** [comment]
I am in Beijing now. Will take some time to add this

**Comment by ChiChou** [comment]
@sushi2k Please check out 0.6.0

**Comment by sushi2k** [comment]
Awesome, thanks for considering and implementing it! I just did an `npm install -g passionfruit` again, not sure how else to upgrade and I can see the connect remote button in the UI! Will try to test it in the next weeks. 
Thanks again
